export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_START = "FETCH_CART_START";
export const FETCH_CART_END = "FETCH_CART_END";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";
export const SET_CART = 'SET_CART';

export const SAVE_CART = "SAVE_CART";
export const SAVE_CART_START = "SAVE_CART_START";
export const SAVE_CART_END = "SAVE_CART_END";
export const SAVE_CART_ERROR = "SAVE_CART_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_AMOUNT = "UPDATE_CART_AMOUNT";
export const UPDATE_CART_TOTAL = "UPDATE_CART_TOTAL";

export const FETCH_CART_OFFERS_START = "FETCH_CART_OFFERS_START";
export const FETCH_CART_OFFERS_END = "FETCH_CART_OFFERS_END";
export const FETCH_CART_OFFERS_ERROR = "FETCH_CART_OFFERS_ERROR";
export const SET_OFFERS = "SET_OFFERS";
export const SET_BEST_OFFER = "SET_BEST_OFFER";
